-- Create customers table
CREATE TABLE IF NOT EXISTS customers (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    email TEXT,
    name TEXT,
    ltv NUMERIC,
    total_spent NUMERIC,
    last_purchase TIMESTAMP WITH TIME ZONE,
    status TEXT CHECK (status IN ('Whale', 'Promising', 'At Risk')),
    source TEXT CHECK (source IN ('Google Ads', 'SEO', 'Meta', 'Direct', 'TikTok', 'LinkedIn'))
);

-- Create budget_scenarios table
CREATE TABLE IF NOT EXISTS budget_scenarios (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID, -- Optional, if we want to link to specific user
    name TEXT,
    allocations JSONB,
    projected_revenue NUMERIC,
    projected_roas NUMERIC,
    total_budget NUMERIC
);

-- Insert 50 mock rows with Sources
INSERT INTO customers (email, name, ltv, total_spent, last_purchase, status, source) VALUES
('alice.zhang@example.com', 'Alice Zhang', 12500.00, 12500.00, NOW() - INTERVAL '2 days', 'Whale', 'Google Ads'),
('bob.chen@example.com', 'Bob Chen', 850.50, 850.50, NOW() - INTERVAL '15 days', 'Promising', 'Meta'),
('charlie.wu@example.com', 'Charlie Wu', 200.00, 200.00, NOW() - INTERVAL '45 days', 'At Risk', 'SEO'),
('david.liu@example.com', 'David Liu', 5400.00, 5400.00, NOW() - INTERVAL '5 days', 'Whale', 'Direct'),
('eva.lin@example.com', 'Eva Lin', 3200.00, 3200.00, NOW() - INTERVAL '1 day', 'Whale', 'Google Ads'),
('frank.wang@example.com', 'Frank Wang', 150.00, 150.00, NOW() - INTERVAL '60 days', 'At Risk', 'Meta'),
('grace.huang@example.com', 'Grace Huang', 980.00, 980.00, NOW() - INTERVAL '12 days', 'Promising', 'TikTok'),
('henry.yang@example.com', 'Henry Yang', 4500.00, 4500.00, NOW() - INTERVAL '3 days', 'Whale', 'SEO'),
('irene.hsu@example.com', 'Irene Hsu', 670.00, 670.00, NOW() - INTERVAL '20 days', 'Promising', 'Google Ads'),
('jack.tsai@example.com', 'Jack Tsai', 120.00, 120.00, NOW() - INTERVAL '50 days', 'At Risk', 'Direct'),
('kelly.chang@example.com', 'Kelly Chang', 8900.00, 8900.00, NOW() - INTERVAL '4 days', 'Whale', 'Meta'),
('leo.cheng@example.com', 'Leo Cheng', 340.00, 340.00, NOW() - INTERVAL '25 days', 'Promising', 'LinkedIn'),
('mina.yeh@example.com', 'Mina Yeh', 1800.00, 1800.00, NOW() - INTERVAL '8 days', 'Promising', 'SEO'),
('nathan.kuo@example.com', 'Nathan Kuo', 55.00, 55.00, NOW() - INTERVAL '90 days', 'At Risk', 'Google Ads'),
('olivia.liao@example.com', 'Olivia Liao', 12000.00, 12000.00, NOW() - INTERVAL '1 day', 'Whale', 'Meta'),
('peter.hung@example.com', 'Peter Hung', 430.00, 430.00, NOW() - INTERVAL '18 days', 'Promising', 'TikTok'),
('quinn.peng@example.com', 'Quinn Peng', 2100.00, 2100.00, NOW() - INTERVAL '7 days', 'Promising', 'Direct'),
('rachel.su@example.com', 'Rachel Su', 95.00, 95.00, NOW() - INTERVAL '35 days', 'At Risk', 'Google Ads'),
('sam.chou@example.com', 'Sam Chou', 6700.00, 6700.00, NOW() - INTERVAL '2 days', 'Whale', 'SEO'),
('tina.lu@example.com', 'Tina Lu', 1100.00, 1100.00, NOW() - INTERVAL '10 days', 'Promising', 'Meta'),
('victor.shieh@example.com', 'Victor Shieh', 250.00, 250.00, NOW() - INTERVAL '28 days', 'Promising', 'LinkedIn'),
('wendy.pan@example.com', 'Wendy Pan', 15000.00, 15000.00, NOW() - INTERVAL '0 days', 'Whale', 'Google Ads'),
('xavier.ho@example.com', 'Xavier Ho', 80.00, 80.00, NOW() - INTERVAL '55 days', 'At Risk', 'Direct'),
('yvonne.ko@example.com', 'Yvonne Ko', 2800.00, 2800.00, NOW() - INTERVAL '6 days', 'Promising', 'Meta'),
('zack.lo@example.com', 'Zack Lo', 4200.00, 4200.00, NOW() - INTERVAL '3 days', 'Whale', 'SEO'),
('aaron.lee@example.com', 'Aaron Lee', 130.00, 130.00, NOW() - INTERVAL '40 days', 'At Risk', 'TikTok'),
('bella.tan@example.com', 'Bella Tan', 700.00, 700.00, NOW() - INTERVAL '16 days', 'Promising', 'Google Ads'),
('cindy.ma@example.com', 'Cindy Ma', 5600.00, 5600.00, NOW() - INTERVAL '4 days', 'Whale', 'Meta'),
('derek.wong@example.com', 'Derek Wong', 2200.00, 2200.00, NOW() - INTERVAL '9 days', 'Promising', 'Direct'),
('elaine.fang@example.com', 'Elaine Fang', 90.00, 90.00, NOW() - INTERVAL '70 days', 'At Risk', 'SEO'),
('felix.jiang@example.com', 'Felix Jiang', 3300.00, 3300.00, NOW() - INTERVAL '5 days', 'Whale', 'Google Ads'),
('gina.hsieh@example.com', 'Gina Hsieh', 500.00, 500.00, NOW() - INTERVAL '22 days', 'Promising', 'Meta'),
('hugo.tseng@example.com', 'Hugo Tseng', 10500.00, 10500.00, NOW() - INTERVAL '1 day', 'Whale', 'TikTok'),
('ivy.chiang@example.com', 'Ivy Chiang', 180.00, 180.00, NOW() - INTERVAL '38 days', 'At Risk', 'Direct'),
('jason.tang@example.com', 'Jason Tang', 950.00, 950.00, NOW() - INTERVAL '14 days', 'Promising', 'SEO'),
('kitty.yu@example.com', 'Kitty Yu', 7800.00, 7800.00, NOW() - INTERVAL '2 days', 'Whale', 'Google Ads'),
('larry.shih@example.com', 'Larry Shih', 290.00, 290.00, NOW() - INTERVAL '30 days', 'Promising', 'Meta'),
('mandy.lien@example.com', 'Mandy Lien', 60.00, 60.00, NOW() - INTERVAL '65 days', 'At Risk', 'LinkedIn'),
('nick.weng@example.com', 'Nick Weng', 4800.00, 4800.00, NOW() - INTERVAL '4 days', 'Whale', 'Direct'),
('ophelia.lai@example.com', 'Ophelia Lai', 1400.00, 1400.00, NOW() - INTERVAL '11 days', 'Promising', 'SEO'),
('paul.chao@example.com', 'Paul Chao', 110.00, 110.00, NOW() - INTERVAL '48 days', 'At Risk', 'Google Ads'),
('queen.sun@example.com', 'Queen Sun', 3600.00, 3600.00, NOW() - INTERVAL '6 days', 'Whale', 'Meta'),
('ryan.chien@example.com', 'Ryan Chien', 550.00, 550.00, NOW() - INTERVAL '19 days', 'Promising', 'TikTok'),
('sophie.tai@example.com', 'Sophie Tai', 9200.00, 9200.00, NOW() - INTERVAL '2 days', 'Whale', 'Direct'),
('tom.kang@example.com', 'Tom Kang', 240.00, 240.00, NOW() - INTERVAL '32 days', 'Promising', 'SEO'),
('una.hsiao@example.com', 'Una Hsiao', 45.00, 45.00, NOW() - INTERVAL '80 days', 'At Risk', 'Google Ads'),
('vicky.ting@example.com', 'Vicky Ting', 6100.00, 6100.00, NOW() - INTERVAL '3 days', 'Whale', 'Meta'),
('william.kAO@example.com', 'William Kao', 800.00, 800.00, NOW() - INTERVAL '15 days', 'Promising', 'LinkedIn'),
('xena.fan@example.com', 'Xena Fan', 160.00, 160.00, NOW() - INTERVAL '52 days', 'At Risk', 'Direct'),
('yuri.chu@example.com', 'Yuri Chu', 1900.00, 1900.00, NOW() - INTERVAL '8 days', 'Promising', 'SEO');
