-- Create the campaigns table
create table if not exists campaigns (
  id bigint generated by default as identity primary key,
  name text not null,
  platform text not null,
  status text not null check (status in ('Active', 'Paused', 'Archived')),
  budget numeric not null default 0,
  spent numeric not null default 0,
  roas numeric not null default 0,
  ctr numeric not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Seed some initial data so it's not empty
insert into campaigns (name, platform, status, budget, spent, roas, ctr)
values
  ('Summer_Sale_Conversion', 'meta', 'Active', 5000, 2300, 3.8, 2.1),
  ('Brand_Keywords_Search', 'google', 'Active', 3000, 1200, 5.2, 4.5),
  ('Viral_Dance_Challenge', 'tiktok', 'Paused', 2000, 800, 1.2, 0.8),
  ('Retargeting_Catalog', 'meta', 'Active', 1500, 1450, 2.9, 1.4),
  ('Shorts_Awareness_001', 'youtube', 'Active', 4000, 500, 1.5, 0.5),
  ('B2B_Lead_Gen_Q3', 'linkedin', 'Active', 6000, 1500, 2.1, 0.9),
  ('Tech_Trends_Thread', 'twitter', 'Paused', 1000, 300, 1.1, 1.2),
  ('Official_Account_Promo', 'line', 'Active', 2000, 1800, 6.5, 3.2),
  ('Competitor_Conquesting', 'google', 'Active', 2500, 2100, 3.1, 2.8),
  ('Influencer_Spark_Ad', 'tiktok', 'Active', 3500, 1200, 3.2, 1.8);
