'use client';

import { getAggregatedMetrics } from '@/lib/mockData';
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow
} from '@/components/ui/table'; // We need to create this or use simple HTML table

export default function ReportPage() {
    const data = getAggregatedMetrics();
    const totalSpend = data.reduce((acc, curr) => acc + curr.spend, 0);
    const totalRevenue = data.reduce((acc, curr) => acc + curr.revenue, 0);
    const roas = totalRevenue / totalSpend;

    return (
        <div className="p-8 bg-white text-black min-h-screen">
            <div className="flex justify-between items-end mb-8 border-b-2 border-black pb-4">
                <div>
                    <h1 className="text-4xl font-bold uppercase tracking-tighter">Lumina AdOS</h1>
                    <p className="text-gray-500">Executive Performance Report</p>
                </div>
                <div className="text-right">
                    <p className="font-bold">Prepared for: Howard</p>
                    <p className="text-sm text-gray-500">{new Date().toLocaleDateString()}</p>
                </div>
            </div>

            <div className="grid grid-cols-3 gap-8 mb-12">
                <div className="p-6 border border-black bg-gray-50">
                    <p className="text-sm text-gray-500 uppercase font-bold mb-2">Total Spend</p>
                    <p className="text-3xl font-bold">${totalSpend.toLocaleString()}</p>
                </div>
                <div className="p-6 border border-black bg-gray-50">
                    <p className="text-sm text-gray-500 uppercase font-bold mb-2">Total Revenue</p>
                    <p className="text-3xl font-bold">${totalRevenue.toLocaleString()}</p>
                </div>
                <div className="p-6 border border-black bg-gray-50">
                    <p className="text-sm text-gray-500 uppercase font-bold mb-2">Blended ROAS</p>
                    <p className="text-3xl font-bold">{roas.toFixed(2)}x</p>
                </div>
            </div>

            <div className="mb-8">
                <h2 className="text-xl font-bold mb-4 uppercase">Daily Performance Breakdown</h2>
                <table className="w-full text-left text-sm border-collapse">
                    <thead>
                        <tr className="border-b border-black">
                            <th className="py-2">Date</th>
                            <th className="py-2">Spend</th>
                            <th className="py-2">Revenue</th>
                            <th className="py-2">ROAS</th>
                            <th className="py-2">Traffic</th>
                        </tr>
                    </thead>
                    <tbody>
                        {data.slice(-14).map((day) => (
                            <tr key={day.date} className="border-b border-gray-200">
                                <td className="py-2">{day.date}</td>
                                <td className="py-2">${day.spend.toLocaleString()}</td>
                                <td className="py-2">${day.revenue.toLocaleString()}</td>
                                <td className="py-2 font-bold">{day.roas.toFixed(2)}x</td>
                                <td className="py-2">{day.clicks.toLocaleString()}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            <div className="mt-12 pt-4 border-t border-gray-300 text-center text-xs text-gray-400">
                Generated by Lumina AdOS Consultant Grade Logic
            </div>
        </div>
    );
}
